### ISSUE TITLE
Option to hide CWStatusBarNotification?

### ISSUE THREAD

**Issue by lilyxl8** [feedfm/iOS-SDK#7]
In our app we don't want the status bar notification (i.e., when song changes) as in iPhone X it messes with our navigation bar layout.
Thanks.

**Comment by eml** [comment]
Hi Lily -
 in FMAudioPlayer, set
disableSongStartNotifications
<http://demo.feed.fm/sdk/docs/ios/4.2.0-beta/html/Classes/FMAudioPlayer.html#//api/name/disableSongStartNotifications>


to NO and those notifications will be disabled.

Eric...

**Comment by eml** [comment]
Oops, I mean YES.

Eric...
