### ISSUE TITLE
Can't get station sometimes on iOS 12

### ISSUE THREAD

**Issue by ZmicierBiesau** [feedfm/iOS-SDK#8]
I'm calling on iOS 12

```
let playerFM = FMAudioPlayer.shared()
        playerFM?.whenAvailable({ [weak playerFM] in
            let station = playerFM?.getStationWithOptionKey("id", value: stationId)
            playerFM?.setActiveStation(station, withCrossfade: false)
            playerFM?.prepareToPlay()
            
            playerFM?.mixVolume = SoundVolumeManager.shared.feedFMVolume
            playerFM?.disableSongStartNotifications = true
            playerFM?.crossfadeInEnabled = true
            playerFM?.secondsOfCrossfade = 3.0
            playerFM?.play()
        }, notAvailable: {
            print("Not available")
        }) 
```
But sometimes player is never available. Everything is ok on iOS 11.4

**Comment by eml** [comment]
Hi Zmicier -
  thanks for this report. We are in the process of testing things out on iOS 12 - we'll take a look at this very soon.

Eric...

**Comment by arvkmr** [comment]
Hi @ZmicierBiesau , I have been unable to reproduce this issue on a iOS 12 simulator.  Are you still having this issue? Did you encounter this on a actual device or a simulator?
-Arveen

**Comment by ZmicierBiesau** [comment]
Hi @arvkmr during at least last two weeks I have never get into this situation again, so looks like now everything is ok. Thank you.
