### ISSUE TITLE
setting secondsOfCrossfade time to 0.5 causes music to stop

### ISSUE THREAD

**Issue by eml** [feedfm/iOS-SDK#9]
This is showing up in the logs:

[FMMixingAudioPlayer applyFadeInAndFadeOutToPlayer:andAttachCrossfadeEvent:andSkipFadeIn:] (642): Fade out from 226.398000 to 0.000000 is invalid?

**Comment by arvkmr** [comment]
A float value was incorrectly being set to int and that was causing any decimal values to be lost so 0.5 crossfade would actually be 0.000 seconds. and 1.5 would 1.0000. 
Fixed in latest commit. Should be included in version 4.2.0
